[storage]
node-1 ansible_host=192.0.2.11 ansible_user=root

[storage:vars]
storage_profile=c4
nic_type=1823
storctl_remote_bin=/usr/local/bin/storctl
storctl_artifact_dir=/root/storage_pkgs
storctl_profile_file=/etc/storctl/profiles.json
