[storage]
node-1 ansible_host=192.0.2.11 storage_nic=enp23s0f1 nic_type=1823 storage_profile=c4
node-2 ansible_host=192.0.2.12 storage_nic=enp194s0f1np1 nic_type=cx7 storage_profile=c4

[storage:vars]
ansible_user=root
storctl_remote_bin=/usr/local/bin/storctl
storctl_artifact_dir=/root/storage_pkgs
storctl_profile_file=/etc/storctl/profiles.json
